/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectografos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import proyectografos.ExceptionesNroVerticeInvalidos;

/**
 *
 * @author hp
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
     private String []ciudades={"SANTA CRUZ","BENI","PANDO","LA PAZ","ORURO","POTOSI","SUCRE","COCHABAMBA","TARIJA"};
     private double[]posicionDeLaCiudad={(double)0,(double)1,(double)2,(double)3,(double)4,(double)5,(double)6,(double)7,(double)8};
     private int []puntosX={349,194,150,117,127,156,255,204,260};
     private int []puntosY={304,217,103,223,369,479,420,317,491};
     private DigrafoPesado miDigrafo;
     private Disjktra dis;
     public form() throws ExceptionesNroVerticeInvalidos, ExceptionAristaYaExiste {
      
        miDigrafo=new DigrafoPesado(9);
        miDigrafo.insertarArista(0,1,5);
        miDigrafo.insertarArista(0,7,2);
        miDigrafo.insertarArista(1,0,8);
        miDigrafo.insertarArista(1,3,20);
        
        miDigrafo.insertarArista(2,1,8);
        miDigrafo.insertarArista(2,3,30);
        miDigrafo.insertarArista(2,0,25);
        
        miDigrafo.insertarArista(3,2,10);
        miDigrafo.insertarArista(3,1,1);
        miDigrafo.insertarArista(3,4,5);
        
        miDigrafo.insertarArista(4,3,15);
        miDigrafo.insertarArista(4,7,2);
        miDigrafo.insertarArista(4,5,20);
        miDigrafo.insertarArista(4,6,9);
        
        miDigrafo.insertarArista(5,8,30);
        
        miDigrafo.insertarArista(6,0,30);
        miDigrafo.insertarArista(6,8,20);
        
        miDigrafo.insertarArista(7,3,1);
        miDigrafo.insertarArista(7,1,10);
        miDigrafo.insertarArista(7,4,12);
        miDigrafo.insertarArista(7,6,12);
        miDigrafo.insertarArista(7,5,80);
        
        miDigrafo.insertarArista(8,0,70);
        // miDigrafo.insertarArista(8,6,15);
        
        initComponents(); 
        
    }
    
     
    
    
     
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jLabel2.setText("CIUDAD DE ORIGEN");

        combo1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz", "Beni", "Pando", "La Paz", "Oruro", "Potosi", "Sucre", "Cochabamba", "Tarija" }));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        jLabel3.setText("CIUDAD DE DESTINO");

        combo2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz", "Beni", "Pando", "La Paz", "Oruro", "Potosi", "Sucre", "Cochabamba", "Tarija" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectografos/mapaDeBoliviaVerde.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("CALCULAR RUTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("DISTANCIA MINIMA DE LA RUTA");

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("RUTA A SEGUIR");

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButton2))
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       //JOptionPane.showInputDialog(this.getMousePosition().getLocation());
       
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int origen=combo1.getSelectedIndex();
        int destino=combo2.getSelectedIndex();
        dis=new Disjktra(this.miDigrafo);
         try {
             
             List<Double>lista=dis.caminosMasCortos(origen, destino);
             total.setText(lista.get(0).toString());
             //lista.remove(0);
             lista.remove(0);
             String s="";
             for(int i=0;i<lista.size();i++){
                 
                 int n=0;
                 //String k=lista.get(i).toString();
                n=(int)Math.round(lista.get(i));
                 s=s+ciudades[n];
                 //s=s+lista.get(i);
                 s=s+"\n";
             }
             s=s+ciudades[destino];
             area1.setText(s);
             Graphics g=getGraphics();
             
             pintarRuta(lista,origen,destino,g);
            
         } catch (ExceptionAristaNoExiste ex) {
             Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void pintarRuta(List<Double>lista,int origen,int destino,Graphics g){
        
        // g=getGraphics();
        
        BasicStroke grueso=new BasicStroke(3);
        Graphics2D linea=(Graphics2D)g;
        linea.setStroke(grueso);
        linea.setColor(Color.black);
        int x1=0;
        int y1=0;
        int x2=0;
        int y2=0;
        lista.add((double)destino);
        for(int i=0;i<lista.size()-1;i++){
            
            x1=puntosX[(int)Math.round(lista.get(i))];
            y1=puntosY[(int)Math.round(lista.get(i))];
            x2=puntosX[(int)Math.round(lista.get(i+1))];
            y2=puntosY[(int)Math.round(lista.get(i+1))];
            
            linea.drawLine(x1, y1, x2, y2);
        }
        x1=x2;
        y1=y2;
        x2=puntosX[destino];
        y2=puntosY[destino];
        linea.drawLine(x1, y1, x2, y2);
        //this.repaint();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form().setVisible(true);
                } catch (ExceptionesNroVerticeInvalidos ex) {
                    Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExceptionAristaYaExiste ex) {
                    Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        });
    }
   

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        //DIBUJAR LOS PUNTOS O MARCADORES DE CIUDADES
        g.setColor(Color.red);//PANDO,ROJO
        g.fillOval(143,96,15,15);
        g.setColor(Color.blue);//LA PAZ AZUL
        g.fillOval(111,218,15,15);
        g.setColor(Color.pink);//BENI ROSADO
        g.fillOval(185,211,15,15);
        g.setColor(Color.cyan);//ORURO CYAN
        g.fillOval(120,360,15,15);
        g.setColor(Color.orange);//POTOSI ANARANJADO
        g.fillOval(148,473,15,15);
        g.setColor(Color.yellow);//COCHABAMBA AMARILLO
        g.fillOval(198,311,15,15);
        g.setColor(Color.white);//SANTA CRUZ BLANCO
        g.fillOval(341,297,15,15);
        g.setColor(Color.darkGray);//SUCRE DARKGRAY
        g.fillOval(246,413,15,15); 
        g.setColor(Color.magenta);//TARIJA MAGENTA
        g.fillOval(254,488,15,15);
       // this.pintar(g);
        
         
        //this.pintar(g);
        
       //-**************************************************
        //DIBUJAR LAS ARISTAS(CAMINOS) QUE SALEN DE UN DEPARTAMENTO A OTRO
            g.setColor(Color.red);//PANDO,ROJO
            g.drawLine(161,113,343,288); //PANDO A SC
            g.fillOval(343,288,7,7);
            g.drawLine(153,117,188,201);//PANDO A BENI
            g.fillOval(188,201,7,7);
            g.drawLine(140,109,118,207);//PANDO A LA PAZ
            g.fillOval(118,207,7,7);
            
            /*********************************/
            g.setColor(Color.pink);//BENI ,AZUL
            g.drawLine(203, 223, 337, 300);//BENI A SC
            g.fillOval(337-2, 300-2,7,7);
            g.drawLine(185,211, 132,222);// BENI A LA PAZ
            g.fillOval(132-2, 222-2,7,7);
            
            /*********************************/
            g.setColor(Color.blue);
            g.drawLine(125,218,144,117);// LA PAZ A PANDO
            g.fillOval(144-3,117-3,7,7);
            g.drawLine(129,231,176,225);//LA PAZ A BENI
            g.fillOval(176-1,223-1,7,7);
            g.drawLine(118,237,128,351);// LA PAZ ORURO
            g.fillOval(128-2,351-2,7,7);
            
            /*********************************/
            g.setColor(Color.cyan);
            g.drawLine(119,351,111,236);//ORURO A LA PAZ
            g.fillOval(111-2,236-2,7,7);
            g.drawLine(120,360,150,468);//ORURO A POTOSI
            g.fillOval(150,468,7,7);
            g.drawLine(120,360,238,410);//ORURO A SUCRE
            g.fillOval(238,410,7,7);
            g.drawLine(138,358,193,325);//ORURO A CBBA
            g.fillOval(192,322, 7,7);
            
            /*********************************/
            g.setColor(Color.orange);
            g.drawLine(166,479,244, 492);//POTOSI A TARIJA
            g.fillOval(244, 492, 7,7);
            
            /*********************************/
            g.setColor(Color.magenta);
            g.drawLine(264,485,342, 319);//TARIJA A SC
            g.fillOval(339, 319, 7,7);
            
             /*********************************/
             g.setColor(Color.yellow);
             g.drawLine(210,330,247,403);// CBBA A SUCRE
             g.fillOval(247,403,7,7);
             g.drawLine(202,332,161,460);// CBBA A POTOSI
             g.fillOval(159-1,460,7,7);
             g.drawLine(192,317,134,352);// CBBA A ORURO
             g.fillOval(134,352-3,7,7);
             g.drawLine(192,310,128,235);// CBBA A LA PAZ
             g.fillOval(128-2,235-2,7,7);
             g.drawLine(203,305,192,229);// CBBA A BENI
             g.fillOval(192-2,229-2,7,7);
             
             /********************************/
             g.setColor(Color.darkGray);
             g.drawLine(261,409,337,317);// SUCRE A SC
             g.fillOval(337-2,317-2,7,7);
             g.drawLine(251,432,258,477);// SUCRE A TARIJA
             g.fillOval(258-2,477,7,7);
             
             /********************************/
             g.setColor(Color.white);
             g.drawLine(336,290,203,215);// SC A BENI
             g.fillOval(203-2,215-2,7,7);
              g.drawLine(330,307,220,316);// SC A CBBA
             g.fillOval(220-2,316-2,7,7);
              
        //MARCAR AZUL PARA PRUEBA
        g.setColor(Color.black);
        g.drawString("30",122,149);
        g.drawString("8",173,161);
        g.drawString("25",255,202);
        g.drawString("10",142,167);
        g.drawString("1",149,231);
        g.drawString("5",126,294);
        g.drawString("20",153,212);
        g.drawString("8",253,263);
        g.drawString("5",253,239);
        g.drawString("2",265,307);
        g.drawString("10",201,273);
        g.drawString("1",159,266);
        g.drawString("12",153,331);
        g.drawString("9",178,415);
        g.drawString("12",228,360);
        g.drawString("2",163,350);
        g.drawString("15",100,323);
        g.drawString("9",208,394);
        
        g.drawString("20",121,429);
        g.drawString("30",201,480);
        g.drawString("20",255,441);
        
        g.drawString("70",311,402);
        g.drawString("30",281,361);
        
       /* Graphics2D linea=(Graphics2D)g;
        BasicStroke grueso=new BasicStroke(5);
        linea.setStroke(grueso);
        linea.setColor(Color.black);
        linea.drawLine(161, 113,343, 288);*/
        
        
        
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
